name: pages-build-deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # On envoie la racine du dépôt en artefact
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./

      # On déploie l'artefact créé
      - uses: actions/deploy-pages@v4
